@csrf
@if ($isSuperAdmin)
    <div class="mb-5"><label class="form-label required">Tenant</label><select name="tenant_id" class="form-select form-select-solid" required><option value="">Select tenant</option>@foreach($tenants as $tenant)<option value="{{ $tenant->id }}" @selected(old('tenant_id', $selectedTenant?->id) == $tenant->id)>{{ $tenant->name }}</option>@endforeach</select></div>
@endif
<div class="row g-6">
    <div class="col-md-6"><label class="form-label required">Program</label><select name="loyalty_program_id" class="form-select form-select-solid" required><option value="">Select program</option>@foreach($programs as $program)<option value="{{ $program->id }}" @selected(old('loyalty_program_id', $rule->loyalty_program_id) == $program->id)>{{ $program->name }}</option>@endforeach</select></div>
    <div class="col-md-6"><label class="form-label required">Rule Name</label><input name="name" value="{{ old('name', $rule->name) }}" class="form-control form-control-solid" required></div>
    <div class="col-md-3"><label class="form-label required">Type</label><select name="rule_type" class="form-select form-select-solid"><option value="spend" @selected(old('rule_type', $rule->rule_type) === 'spend')>Spend</option><option value="bonus" @selected(old('rule_type', $rule->rule_type) === 'bonus')>Bonus</option></select></div>
    <div class="col-md-3"><label class="form-label">Spend Amount</label><input type="number" step="0.01" name="spend_amount" value="{{ old('spend_amount', $rule->spend_amount) }}" class="form-control form-control-solid"></div>
    <div class="col-md-3"><label class="form-label required">Points</label><input type="number" name="points_awarded" value="{{ old('points_awarded', $rule->points_awarded) }}" class="form-control form-control-solid" required></div>
    <div class="col-md-3"><label class="form-label">Minimum Purchase</label><input type="number" step="0.01" name="minimum_purchase_amount" value="{{ old('minimum_purchase_amount', $rule->minimum_purchase_amount) }}" class="form-control form-control-solid"></div>
    <div class="col-md-3"><label class="form-label">Maximum Points</label><input type="number" name="maximum_points_per_transaction" value="{{ old('maximum_points_per_transaction', $rule->maximum_points_per_transaction) }}" class="form-control form-control-solid"></div>
    <div class="col-md-3"><label class="form-label">Branch</label><select name="branch_id" class="form-select form-select-solid"><option value="">All branches</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected(old('branch_id', $rule->branch_id) == $branch->id)>{{ $branch->name }}</option>@endforeach</select></div>
    <div class="col-md-3"><label class="form-label">Service</label><select name="service_id" class="form-select form-select-solid"><option value="">Any service</option>@foreach($services as $service)<option value="{{ $service->id }}" @selected(old('service_id', $rule->service_id) == $service->id)>{{ $service->name }}</option>@endforeach</select></div>
    <div class="col-md-3"><label class="form-label">Product</label><select name="product_id" class="form-select form-select-solid"><option value="">Any product</option>@foreach($products as $product)<option value="{{ $product->id }}" @selected(old('product_id', $rule->product_id) == $product->id)>{{ $product->name }}</option>@endforeach</select></div>
    <div class="col-md-3"><label class="form-label">Start Date</label><input type="date" name="start_date" value="{{ old('start_date', $rule->start_date?->toDateString()) }}" class="form-control form-control-solid"></div>
    <div class="col-md-3"><label class="form-label">End Date</label><input type="date" name="end_date" value="{{ old('end_date', $rule->end_date?->toDateString()) }}" class="form-control form-control-solid"></div>
    <div class="col-md-3"><label class="form-label">Priority</label><input type="number" name="priority" value="{{ old('priority', $rule->priority) }}" class="form-control form-control-solid"></div>
    <div class="col-md-3"><label class="form-label required">Status</label><select name="status" class="form-select form-select-solid"><option value="active" @selected(old('status', $rule->status) === 'active')>Active</option><option value="inactive" @selected(old('status', $rule->status) === 'inactive')>Inactive</option></select></div>
</div>
<div class="text-end mt-8"><button class="btn btn-primary">Save Rule</button></div>
